# {# pkglts, conda.package
package:
  name: pkglts
  version: "2.7.1"
# #}

# {# pkglts, conda.src
source:
  path:
    ../
# #}

requirements:
  build:
    - python
    - setuptools
    - pytest-runner

  run:
    - python
    - jinja2
    - coverage
    - flake8
    - mock
    - nbconvert
    - pytest
    - pytest-cov
    - sphinx
    # - tox # virtualenv
    # - twine
    # - coveralls

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

# {# pkglts, conda.about
about:
  summary: "Building packages with long term support"
  license: "CeCILL-C"
  license_file: LICENSE
# #}
