package:
  name: {{ base.pkg_full_name }}
  version: "{{ version.major }}.{{ version.minor }}.{{ version.post }}"

source:
  path: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

about:
  summary: "{{ doc.description }}"
  license: "{{ license.name }}"
  license_file: LICENSE
