package:
  name: pkglts
  version: "1.2.1"

source:
  path: ../

build:
  number: 0
  entry_points:
    - pmg = pkglts.manage_script:main
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - jinja2

test:
  imports:
    - pkglts

  commands:
    - pmg --help

about:
  summary: "Building packages with long term support"
  license: "CeCILL-C"
  license_file: LICENSE
