package:
  name: pkglts
  version: "1.2.1"

source:
  path: ../

build:
  number: 0
  entry_points:
    - pmg = pkglts.manage_script:main
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner

  run:
    - python
    - jinja2
    - coverage
    - coveralls
    - flake8
    - mock
    - nbconvert
    - pytest
    - pytest-cov
    - sphinx
    - tox
    - twine

test:
  imports:
    - pkglts

  commands:
    - pmg --help

about:
  summary: "Building packages with long term support"
  license: "CeCILL-C"
  license_file: LICENSE
